apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "demo-api-db-migrator.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "demo-api-db-migrator.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "demo-api-db-migrator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["dotnet"]
        args: ["demo-api-db-migrator.dll", "migrate-database"]
        env:
        
        {{- $env := merge (.Values.env | default dict) (.Values.global.env | default dict) -}}
        {{ range $k, $v := $env }}
          - name: {{ $k | quote }}
            value: {{ $v | quote }}
        {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}