apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "audit-service.fullname" . }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    # Override the configuration properties here
    management:
      endpoint:
        health:
          enabled: true
        info:
          enabled: true
        restart:
          enabled: true