apiVersion: v1
kind: Service
metadata:
  name: {{ include "audit-service.fullname" . }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: 172.17.176.130
  ports:
    - port: {{ .Values.service.port }}      
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "audit-service.selectorLabels" . | nindent 4 }}
