apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-portal.fullname" . }}
  labels:
    {{- include "identity-portal.labels" . | nindent 4 }}
data:
  appsettings.Development.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      },
      "SecretProvider": {
        "Name": "LocalStack",
        "Enabled": true,
        "Url": "http://192.168.1.38:4566",
        "AuthKey": "CLOUD",
        "ApplicationId": "CLOUD"
      },
      "ApiDeploymentOptions": {
        "Host": "demo-cluster-identity-api.iaas-1",
        "UseSSL": false
      },
      "OidcSettings": {
        "AliasStrategy": "Segment",
        "Options": [
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii",
            "ClientId": "identity-portal",
            "PersonaType": "EndUser",
            "ResponseType": "code",
            "Name": "Default SP",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.121/{segment}/portal",
            "AdditionalProviderParameters": {
              "acr_values": "urn:fischer:loa:1fa:pwd"
            }
          }          
        ]
      },
    }