apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "identity-portal.fullname" . }}
  labels:
    {{- include "identity-portal.labels" . | nindent 4 }}
data:
  appsettings.overrides.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      },
      "SecretProvider": {
        "Name": "LocalStack",
        "Enabled": true,
        "Url": "http://192.168.1.38:4566",
        "AuthKey": "CLOUD",
        "ApplicationId": "CLOUD"
      },
      "ApiDeploymentOptions": {
        "Host": "demo-cluster-identity-api.iaas-1",
        "UseSSL": false
      }      
    }
  appsettings.oidc.json: |-
    {      
      "OidcSettings": {
        "AliasStrategy": "Segment",
        "Options": [
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii1",
            "ClientId": "identity-portal",
            "PersonaType": "EndUser",
            "ResponseType": "code",
            "Name": "Default SP",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.120/{segment}/portal",
            "AdditionalProviderParameters": {
              "acr_values": "urn:fischer:loa:1fa:pwd"
            }
          },
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii",
            "ClientId": "identity-portal-helpdesk",
            "PersonaType": "DelegatedAdministrator",
            "ResponseType": "code",
            "Name": "Default SP",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.120/{segment}/manager",
            "AdditionalProviderParameters": {
              "acr_values": "urn:fischer:loa:1fa:pwd"
            }
          },
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii",
            "ClientId": "identity-portal-admin",
            "PersonaType": "Administrator",
            "ResponseType": "code",
            "Name": "Default SP",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.120/{segment}/admin",
            "AdditionalProviderParameters": {
              "acr_values": "urn:fischer:loa:2fa:any"
            }
          },
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii",
            "ClientId": "impersonated-user-token",
            "ResponseType": "code",
            "Name": "Kiosk: Impersonated User",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.120/{segment}/kiosk"
          },
          {
            "Authority": "https://ebs-v80-qa-20-sso.fischeridentitydev.com/auth/realms/fii",
            "ClientId": "impersonated-user-token",
            "ResponseType": "code",
            "Name": "Claim: Impersonated User",
            "Segments": "fii,code,ops",
            "UrlPath": "172.17.176.120/{segment}/portal/claim"
          }
        ]
      },
    }