apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-api.fullname" . }}
  labels:
    {{- include "demo-api.labels" . | nindent 4 }}
data:
  appsettings.overrides.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      },
      "SecretProvider": {
        "Name": "AWS",
        "AuthKey": "xxxxxxxxxxxx12345"
      }
    }